name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust Toolchain for GitHub CI
      # You may pin to the exact commit or the version.
      # uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8
      uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
      with:
        # Comma-separated list of Rust toolchain specifications. Last version becomes the default. -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
        toolchain: nightly
    - name: Check with Clippy
      run: cargo clippy --verbose --all-targets --all-features
    - name: Store target
      uses: actions/upload-artifact@v4
      with:
        name: target
        path: target
        retention-days: 1
        overwrite: true
        include-hidden-files: true

  build:
    needs: check

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust Toolchain for GitHub CI
      # You may pin to the exact commit or the version.
      # uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8
      uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
      with:
        # Comma-separated list of Rust toolchain specifications. Last version becomes the default. -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
        toolchain: nightly
    - name: Download target
      uses: actions/download-artifact@v4
      with:
        name: target
    - name: Build
      run: cargo build --verbose
    - name: Store target
      uses: actions/upload-artifact@v4
      with:
        name: target
        path: target
        retention-days: 1
        overwrite: true
        include-hidden-files: true

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust Toolchain for GitHub CI
      # You may pin to the exact commit or the version.
      # uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8
      uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
      with:
        # Comma-separated list of Rust toolchain specifications. Last version becomes the default. -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
        toolchain: nightly
    - name: Download target
      uses: actions/download-artifact@v4
      with:
        name: target
    - name: Test
      run: |
        cargo test --verbose --bins --examples --tests --benches --all-targets --all-features
        cargo test --verbose --doc --all-features
